### ISSUE TITLE
some LED's don't turn off on the D#2 and A#1 pads in the drum sequencer

### ISSUE THREAD

**Issue by rasputozen** [hdavid/Launchpad95#16]
On just these pads there are 2-3 note positions where the LED light won't change to indicate a note on/off.  I moved all the pads down an octave and up an octave and this problem went away both times... so it seems like it's just these two pads.  The buttons still function to turn notes on/off but they don't receive an off message it seems, at least on my setup.

**Comment by hdavid** [comment]
could not reproduce.
it could be indeed linked, as you say that your drum rack it grouped.
