### ISSUE TITLE
Change session clip stop buttons to become clip delete buttons if the track is stopped. 

### ISSUE THREAD

**Issue by thomasf** [hdavid/Launchpad95#25]
I'm thinking that all of the bottom row would have the same delete clip function and that it turns red while being pressed so that any clip can be deleted if it's selected.

This would make it possible to do the most essential clip management directly from the session view. 

What do you think about this proposition?

**Comment by hdavid** [comment]
frankly i dont have much time to do it and it would require patching the base code in _Framework that i prefer to avoid. but maybe we could use the stop button as a modifier and then delete it.

feel free to come up with a pull request :)

**Comment by thomasf** [comment]
I was looking at this issue a few days ago as well and thought that I might have changed my mine. I'm leaning more towards one function per screen per button kind of flow because it quickly gets confusing otherwise.

What I probably really want is novation to release a launch pad pro wide mini with 16x8 grid buttons :) I love my dual lp mini setup but two full size lp pro's would just be taking up to much space for what I want to do so I'm still waiting/hoping for something awsome in the LP midi+pro combination at some point.
