### ISSUE TITLE
No lights feedback anymore in combined mode when coming back from multi note mode

### ISSUE THREAD

**Issue by spoutnikz** [hdavid/Launchpad95#27]
Hello there,

First of all it's a fantastic work, love it!

I have noticed a case where I have no more note lights feedback in step sequencer Combined mode. It's a weird state, some lights which were on in multi mode stays in combined mode. Restarting Ableton is the only way found so far to reset it.

Currently I avoid using the multi note mode. I've spent some hours playing with your script and so far this clip page navigation bug makes the multi note mode not usable on my gear.

System:
- launchpad mini
- ableton live suite 9.6 32bit

Steps to reproduce:
1) user mode 2 (brings step sequencer Combined mode)
2) 4th scene button (brings step seqencer Multi note mode)
3) right button (moves clip page to the right) (that's the problematic action)
4) 4th scene button again (brings the Combined mode again)

I can provide further details if needed (steps, video,...).
I'll read the source code too but it's a long time since my last python script and I have never done any music script. Anyway I will try, maybe make a pull request if I find anything.

Thanks for the nice script,

spoutnik

**Comment by spoutnikz** [comment]
@see https://github.com/hdavid/Launchpad95/pull/28

**Comment by hdavid** [comment]
merged ! thanks a lot :)
