### ISSUE TITLE
Commit  3fe8d20e2421b9531305e7e0a1417a69bf5bf55e  stopped working with my launchpad S

### ISSUE THREAD

**Issue by alexjbest** [hdavid/Launchpad95#36]
Hi there,

I recently tried to update my launchpad95 script to the latest in the repo but I couldn't get my launchpad model s to work with it, I tried all the previous commits and found that it did work for commit ae872f3... but not for 3fe8d20e2421b9531305e7e0a1417a69bf5bf55e is this expected?

I'm happy to provide more information, thanks for the cool scripts!

Alex

**Comment by hdavid** [comment]
Hi,

i dont have a launchpad S (only mini mk2, mk2 and pro...). is this still happening ?
