### ISSUE TITLE
RemoteScriptError (Launchpad MK1 + Ableton 9.2.2)

### ISSUE THREAD

**Issue by MatiasBontempo** [hdavid/Launchpad95#47]
Hi! I just tried to install this script but whenever I pick Launchpad95 from the midi menu the device seems unresponsive. It still sends midi to Ableton, but the script is not working. This is the error I see in the log file when I select Launchpad and then Launchpad95:

80177 ms. RemoteScriptMessage: (Launchpad) Initialising...
82923 ms. RemoteScriptMessage: (Launchpad) Initialising...
83779 ms. RemoteScriptMessage: (Launchpad) Challenge Response ok (mk1)
83789 ms. RemoteScriptError: Traceback (most recent call last):

83794 ms. RemoteScriptError:   File "c:\Jenkins\live\output\win_64_static\Release\midi-remote-scripts\_Framework\ControlSurface.py", line 456, in receive_midi

83798 ms. RemoteScriptError:   File "c:\Jenkins\live\output\win_64_static\Release\midi-remote-scripts\_Framework\ControlSurface.py", line 467, in _do_receive_midi

83802 ms. RemoteScriptError:   File "MIDI Remote Scripts\Launchpad95\Launchpad.py", line 197, in handle_sysex

83807 ms. RemoteScriptError:     
83811 ms. RemoteScriptError: self.init()

83817 ms. RemoteScriptError:   File "MIDI Remote Scripts\Launchpad95\Launchpad.py", line 120, in init

83821 ms. RemoteScriptError:     
83825 ms. RemoteScriptError: self.log_message("LaunchPad95 Loaded !")

83830 ms. RemoteScriptError:   File "c:\Jenkins\live\Projects\AppWebConnector\Resources\third_party\lib\contextlib.py", line 33, in __exit__

83835 ms. RemoteScriptError:   File "c:\Jenkins\live\output\win_64_static\Release\midi-remote-scripts\_Framework\ControlSurface.py", line 660, in component_guard

83839 ms. RemoteScriptError:   File "MIDI Remote Scripts\Launchpad95\Launchpad.py", line 103, in init

83843 ms. RemoteScriptError:     
83847 ms. RemoteScriptError: self._init_note_repeat()

83851 ms. RemoteScriptError:   File "MIDI Remote Scripts\Launchpad95\Launchpad.py", line 270, in _init_note_repeat

83856 ms. RemoteScriptError:     
83859 ms. RemoteScriptError: self._note_repeat = NoteRepeatComponent(name='Note_Repeat')

83864 ms. RemoteScriptError:   File "MIDI Remote Scripts\Launchpad95\NoteRepeatComponent.py", line 21, in __init__

83868 ms. RemoteScriptError:     
83872 ms. RemoteScriptError: Live.Base.log("NoteRepeatComponent - Init Start")

83876 ms. RemoteScriptError: AttributeError
83881 ms. RemoteScriptError: : 
83885 ms. RemoteScriptError: 'module' object has no attribute 'log'
83889 ms. RemoteScriptError: 

Thanks!

**Comment by hdavid** [comment]
hi,

we are at live 9.7 now. please update your live, it is free. i cannot support all old versions.

regards,

henri
