### ISSUE TITLE
Ableton 9.7.1 does not show Launchpad95 in the Midi settings.

### ISSUE THREAD

**Issue by cuneytyvz** [hdavid/Launchpad95#49]
Hello,

I’m trying to make Launchpad95 Scripts work on Ableton 9.7.1. I have copied the unzipped Launchpad95 folder into /Users/…/Library/Preferences/Ableton/Live 9.7.1/User Remote Scripts/
But in the Preferences/Midi tab I cannot see Launchpad95 script. Only Launchpad is shown which is already seen without custom scripts. Because of that new scripts does not work. What might be the cause?

**Comment by hdavid** [comment]
please read the manual which explains in very much details where to put the script and certainly does not point to /Users/…/Library/Preferences/Ableton/Live 9.7.1/User Remote Scripts/ ,)

http://motscousus.com/stuff/2011-07_Novation_Launchpad_Ableton_Live_Scripts/#faq-3
