### ISSUE TITLE
Move position of launched note in drum rack 

### ISSUE THREAD

**Issue by gonzaloamadio** [hdavid/Launchpad95#50]
I am in user 1 mode. I select a channel with a drum rack and arm it.
When I press the leftmost bottom button , it launches the C3 note, and the rest of the buttons, from that note upwards.
I want to be able to move that, so it launches the C1 note. But I cant find how to do it

**Comment by jimmypringles** [comment]
Hi,
If I understood you correctly, you will want to hit the octave up button twice.
![image](https://user-images.githubusercontent.com/12073626/59738906-c9db3400-9217-11e9-9275-194d521473df.png)

**Comment by hdavid** [comment]
tested and works as expected.
