### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by matdombrock** [hdavid/Launchpad95#52]
Will it continue to be updated for new versions of ableton?

**Comment by hdavid** [comment]
hi, 
Dead: no. Dormant: maybe ,)
it will continue to work just fine if ableton does not break the compatibility in a major way and makes it hard or impossible to fix. 
that said the changes required when live was upgraded from 9 to 10 were minimal.
Also, as this is an opensource project, anyone is welcome to contribute :)

cheers,

henri
