### ISSUE TITLE
Changing the color of drum pads?

### ISSUE THREAD

**Issue by matdombrock** [hdavid/Launchpad95#53]
For large drum kits on the MKII, it could be very useful to be able to change the color of the drum pads. For instance, making hi-hats and toms a different color than kicks and snares. 

I've read over the user manual and couldn't find any way to do this.

However, it is possible to change the color of the drum hits in the Ableton drum rack. (Screenshot below)

![Capture](https://user-images.githubusercontent.com/1508293/62662527-3aa1f100-b929-11e9-9ce5-50c579b7b0ee.PNG)

Is there any way to translate these colors to the Launchpad? 

Since there is nothing in the manual that I could find I'm assuming the code doesn't have a way to handle this. Working on that assumption, is this even possible? 

If it is possible but just not supported, I'm interested in taking a shot at implementing this. I have a pretty good grasp on Python and the code is generally making sense to me, but if you could point me in the right direction on this that would be much appreciated!

**Comment by hdavid** [comment]
Hi, 
unfortunately it is not possible. also as far as know this is colouring the chain elements, not the pads. sorry
