### ISSUE TITLE
Launchpad X combined Session/Mixer Mode

### ISSUE THREAD

**Issue by nilssanders** [hdavid/Launchpad95#57]
Hi Henri, 
I love your work at Launchpad95! Thank you so much! Today I get my new Launchpad X and I try the newest Launchpad95 version. Sadly the new combined Session/Mixer Mode I like so much with the new Launchpad X is not working. Are you still working on it? Just the default X plus the step Sequenzer in Custom mode would be sooooo great ;-)
Anyway... love your work,
Nils

**Comment by hdavid** [comment]
Hi 
I am not sure you are referring to by "combined Session/Mixer Mode".
if you are mentioning a mode that is available on the X with the stock scripts, then yes it wont be available.

**Comment by nilssanders** [comment]
Hi,

thanks for your replay! Yes, I’m talking about a stock script. The mode where you view your Session clips and the bottom row is able to show the mute or solo buttons. I love this mode. Anyway… ;-)

Thanks again,
Nils




/

BÆUCKER SANDERS GmbH

Nils Sanders
+49 151 10928701
nils@baeucker-sanders.com

Berlin / Germany
www.baeucker-sanders.com

Registergericht: Amtsgericht Charlottenburg
Registernummer: HRB 167623 B

/
