### ISSUE TITLE
Some issues I found

### ISSUE THREAD

**Issue by canuysal** [hdavid/Launchpad95#59]
Hi, first of all your work is great. I can't describe how much I appreciate it. I was almost gonna toss my mk2 away when I found your scripts.

I noticed few things while using launchpad95, I might not know how to use it, or they might be an issue, so here it goes.

- In session mode, if I press one of the clips, track gets armed and I can't disable any clips from it after that.
- In drum/melodic sequencer mode, if i hold mute to extend range with copying, only first loop region gets copied to new ones. I suppose it should copy the ones first clicked to the ones that clicked later. But its always only the first region.

Also, if I can ask a question, whats the purpose of implicit arm? Cant seem to figure it out.

**Comment by canuysal** [comment]
I can send a PR on it by the way, if you tell me where to look for. I'm not too familiar with python but I can do it.

**Comment by hdavid** [comment]
thanks for you proposal ! sure yes have a go at it.
to be honest i would not know where to start. :/
also, note that Ableton 11 beta has just be announced and it will require some changes, as python version is upgraded there.

**Comment by canuysal** [comment]
Oh thanks for the heads up, but I'm not planning to upgrade to ableton 11 soon.

Which script is responsible of session view - arm track after I press one of the clips? To be more specific, my problem is when I press any of the clip, that track gets armed and empty clip zones appears red and starts recording if i press them. I just wanna be able to play clips and stop them in session mode.

Which script is responsible of duplicating of current region in user2-multi/combined mode?

**Comment by hdavid** [comment]
to be honest, i wrote these scripts many years ago, i dont remember exactly.

about extending a clip, search for "_extend_clip_content" in the sources.

about the arming, i suppose live automatically arm the selected track, but i dont recall where or how it is controlled

**Comment by jimmypringles** [comment]
If I understand the behavior described, the auto arming is the "arm on selection" Ableton feature. That can be configured in ableton user preferences under 
**Windows:** \Users\Username\AppData\Roaming\Ableton\Live x.x.x\Preferences\Options.txt
**Mac OS X:** \User\Library\Preferences\Ableton\Live x.x.x\Options.txt

In my case (windows 10) the only entry under options was "-EnableArmOnSelection" and I replaced it with "-NoAutoArming" which stops this behavior after a restart.
![image](https://user-images.githubusercontent.com/12073626/99131526-423e5400-25c8-11eb-9270-3285a11c466b.png)
