### ISSUE TITLE
I redesigned/re-edited the manual.

### ISSUE THREAD

**Issue by jeremymeyers** [hdavid/Launchpad95#60]
Hey there-

As a random weekend COVID project, I redid the manual in a more graphical style, and made a bunch of edits to the content wording and organization to make it clearer (I think). I did reach out to @hdavid but didn't hear back so wanted to post it here. https://launchpad95manual.mystrikingly.com/  (i'm happy to make any adjustments or changes or anything)

**Comment by hdavid** [comment]
Hi Jeremy! 
thanks for the  work on the manual :)
indeed the manual could use some love and rework. could you reach out via email again (sorry i must have missed your previous email or it went into spam folder.
i would like to see how we could get the best of both world (keep the colour scheme somewhat, keep the full css renders, but at the same time use your new organisation of the page.

cheers

henri

**Comment by jeremymeyers** [comment]
would you let me know your current email address? i cannot promise i can replicate things more precisely (strikingly limits the amount of manual coding one can do, to begin with) but definitely open to hearing your thoughts.

**Comment by hdavid** [comment]
my email is mots@<myWebsite.com> :)
let's have a look at it. also recently updated the manual for the new live11 version!

**Comment by hdavid** [comment]
hi, i did not hear back from you. feel free to ping me.

**Comment by jeremymeyers** [comment]
(did so on slack)
