### ISSUE TITLE
fixed length recording?

### ISSUE THREAD

**Issue by ldrolez** [hdavid/Launchpad95#61]
Hi!

Do you think you could add a fixed length recording option? Like the SRECFIX macro in ClyphX?

Thanks!

**Comment by hdavid** [comment]
Hi, the main problem is that i really dont know which button we could use to configure the length of the recorded clips, as pretty much all buttons are already used, often more than once.
also, while i try to maintain the scripts, adding new features is time consuming, and would require some work.
but if you want to have a go at it and submit a PR, please go for it :)
