### ISSUE TITLE
Settings Menu for Velocity Change?

### ISSUE THREAD

**Issue by mark-zarandi** [hdavid/Launchpad95#62]
The stock launchpad setup has a seperate menu that you bring up by hitting the session button to change settings by velocity.  Is there a way to configure my pad velocity in launchpad95 when im in instrument control mode?

**Comment by hdavid** [comment]
i think this is a feature of the new launchpad scripts. but for the new launchpads, i put them in developer mode, which i suppose might not support this. sorry
