### ISSUE TITLE
Launchpad X with LP95 and Launchkey Mini MK3

### ISSUE THREAD

**Issue by mark-zarandi** [hdavid/Launchpad95#63]
LP95 has been working fine until i started trying to use it with my launchkey mini mk3.  Now whenever both are connected, the LP95 mixer won't come up.  Also, there's a weird white key at the bottom right of session view.  Is there a chance that LP95 is try to impose itself on the LaunchKey mini as well?  Thanks for any advice.

**Comment by mark-zarandi** [comment]
My default template that i set up with baseline drum racks works fine out of the gate, it seems there's something maybe about saving a seperate file that sends the scripts haywire?

**Comment by hdavid** [comment]
hello, i am not sure i will be able to remote debug it. i know that sometime, having multiple scripts create strange interactions. but not having a launchkey myself.
you can try to look at the Log.txt file and see if there is some error
https://help.ableton.com/hc/en-us/articles/209071629-Where-to-find-Crash-Reports
Live's log file can be found here:

Windows - \Users\[username]\AppData\Roaming\Ableton\Live x.x.x\Preferences\Log.txt
Mac - /Users/[username]/Library/Preferences/Ableton/Live x.x.x/Log.txt

**Comment by mark-zarandi** [comment]
Mmm, consider this matter closed.  Your assessment is right.  I cloned your respository to make my own project and saved it under a different name in the same remote scripts directory.  I only had this issue in ONE live set.  Then when i built the live set from scratch after deleting the cloned repo it worked fine.  I've been thinking you could give Novation a run for their money if there was a "Harp" mode?  Where in note mode, each column would be one note in a major chord and then you could switch around like an Auto-harp.
