### ISSUE TITLE
[Feature Request]: Delete clips from session mode

### ISSUE THREAD

**Issue by francesconazzaro** [hdavid/Launchpad95#65]
Hi, great project, thank you for the effort on this!

It would be very useful to have a more straightforward way to delete clips, like the Ableton Push, by holding a button and click on a clip on Session Mode. 
The button to hold could be the Session mode button (it seems that it has no function when hold down), I couldn't find any information in the documentation.

**Comment by hdavid** [comment]
hello, i am working on integrating the Pro Session feature from Launchpad97 :
it is almost ready for prime time! have look at https://github.com/hdavid/Launchpad95/tree/launchpad97
