### ISSUE TITLE
Error message: "uses older process to modify midi notes"

### ISSUE THREAD

**Issue by 4ndrw** [hdavid/Launchpad95#66]
![image](https://user-images.githubusercontent.com/52018186/129605045-47eba3f2-6e08-41b8-834e-670b222766ad.png)
Hey, amazing script!

I noticed I get these error messages in Ableton Live 11 with a launchpad mini mk3, thought I'd pass that on.

**Comment by hdavid** [comment]
thanks for your comment. i am aware of this, but there is just no way to support both live 9/10 and 11 and the same time.
it would also imply rewriting the whole code for the stepsequencer. it just works for now, but you loose the MPE info (which yo cannot edit anyways in the step sequencer)

**Comment by probonopd** [comment]
Also getting this. Does that mean that as soon as one uses Launchpad95, then the aftertouch on the Launchpad X is not usable anymore? I was hoping to use MPE aftertouch with Dexed, which supports MPE. Or is there a way to use the aftertouch without the need for MPE?
