### ISSUE TITLE
Custom User Mode: Novation Librarian?

### ISSUE THREAD

**Issue by mark-zarandi** [hdavid/Launchpad95#67]
Mr. David - Thanks for everything you do for the community.  I haven't removed LP95 from my setup since i got my LP.  I uncommented "user 2" in settings py and loaded a user mode through Novation Librarian, but it's not working.  I made a layout of CC message buttons in Librarian, and it works fine when i deactivate LP95, but when I engaged LP95 it doesn't recognize them.  I saw in your source code where the channel for user mode 1 has to be 4 and user mode 2 has to be 5, but it still won't work.  Thanks for any help if it's something dumb i'm doing, otherwise keep at it with LP97.  I'm stoked to see what you come up with.

Hey BTW, i've had alot of great success with that "quick" scale change setting in note mode.

**Comment by hdavid** [comment]
LP95 was implemented years ago when the component concept did not exist. usermode 1 and 2 are a different thing and cannot be used with components. i am not sure if the script lp95 can be adapted to use them as there are linked to the hw and lp95 put the launchpad in "programmer mode" for backward compat with older launchpad.

**Comment by MrMatch246** [comment]
So this means it is actually impossible to use them together unless actually modifying the firmware etc...
Basically the MPE features are not available in programmer mode?
Or is it "just" a matter of reimplementing their components framework

**Comment by hdavid** [comment]
it is impossible.
