### ISSUE TITLE
live crashes, when editing notes in a clip, which is currently sequenced on the sequencers

### ISSUE THREAD

**Issue by tothbar** [hdavid/Launchpad95#73]
I have this problem quite freqently. unfortunately i dont really know python, so i cant figure it out myself, what should be changed.

**Comment by hdavid** [comment]
if live crashes, there is not much we can do in the script itself unfortunately.
make sure you run the most recent version of live and contact ableton support.

**Comment by tothbar** [comment]
All right! Thanks for your fast response.
