### ISSUE TITLE
Documentation is hard to read due to low contrast

### ISSUE THREAD

**Issue by probonopd** [hdavid/Launchpad95#74]
Hi, great project.

A suggestion from someone just starting out and trying to learn: Currently the documentation is hard to read due to low contrast (somewhat brigher gray letters on somewhat darker gray background). It would be much easier to read if it had more contrast (like black letters on white background).
Thanks for considering.

**Comment by hdavid** [comment]
my site has been running this CSS for years and i dont plan on updating it, sorry.
feel free to download the HTML and tweak the css to change BG and text colours
