### ISSUE TITLE
OSD documentation

### ISSUE THREAD

**Issue by probonopd** [hdavid/Launchpad95#75]
Documentation says:

> For Live Suite users, in the M4LDevice folder is included an OSD (on screen display) Max4Live device that will display information, similarly to what one could see on an Ableton Push screen.
> 
> 
![image](https://user-images.githubusercontent.com/2480569/225987033-796f59a8-20de-4979-ae63-a684976e371c.png)

Unfortunately it is not explained how _exactly_ to get this to work.

It would be very helpful to know what needs to be copied where, and whether Live needs to be restarted. Should the window appear automatically, all the time?

**Comment by hdavid** [comment]
i dont know, just drag the OSD M4L anywhere, on any track. 
boom it opens and display the osd. 
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/566554/225992719-887a0f79-b150-44bf-affa-38dce1740a21.png">

not sure we need to document that ?

**Comment by probonopd** [comment]
> just drag the OSD M4L anywhere, on any track.

Thanks, that's it. Maybe just add that sentence to the docs? I had assumed that one would have to copy it to some folder.
