### ISSUE TITLE
Update documentation to (also) reflect button names on newer Launchpad models

### ISSUE THREAD

**Issue by probonopd** [hdavid/Launchpad95#76]
The Launchpad X has the following buttons (the square ones). I am putting them next to the buttons mentioned in the documentation, which I guess are the buttons from older models (the round ones).

At this point, I am just speculating (but am not really sure) that there is a 1:1 relationship between the old and the new keys.

It would be nice if the documentation would reflect both old and new buttons, since for users of Launchpad X the documentation is constantly referring to non-existing keys.

![image](https://user-images.githubusercontent.com/2480569/225987777-0becdcfe-b81a-488e-92e9-86fa03845aee.png)
![image](https://user-images.githubusercontent.com/2480569/225988393-9f9414da-4d80-443c-be61-af6fd78b5fef.png)

![image](https://user-images.githubusercontent.com/2480569/225987877-491918af-5435-4561-b0ab-835da6f380dd.png) ![image](https://user-images.githubusercontent.com/2480569/225988176-1cd8d793-ffc3-44d0-8b3e-8cce2012abea.png)

**Comment by hdavid** [comment]
as mentioned in a previous ticket, this fixes your problem, but create problem for other users that have different launchpads.
just use the button position instead.

**Comment by probonopd** [comment]
Can you confirm that there should be a 1:1 relationship between the buttons I posted? So for example, "Note" = "user 1 Inst."? 

(Maybe the question sounds a bit sily, but I have a hard time to figure this out for sure, as the behavior doesn't seem to match the documentation, as per my other ticket).

**Comment by hdavid** [comment]
what matter is the position of the button, just ignore the labels.
