### ISSUE TITLE
How to enter Instrument Controller Mode on Launchpad X?

### ISSUE THREAD

**Issue by probonopd** [hdavid/Launchpad95#77]
Documentation says

> Instrument Mode replaces classic User Mode 1. To activate Instrument Controller Mode, press User Mode 1 button (mode button remains amber). Press User Mode 1 button once again, button turns green, activating the Device Controller. Once more the button will turn red, activating the plain old User Mode 1 in case you need it.

However, there is no "User Mode 1" button on the Launchpad X and other newer models.

Instead, the 6th button is labeled "Note".

> Mode 1. To activate Instrument Controller Mode, press User Mode 1 button (mode button remains amber).

Assuming that "Note" is the button that should be pressed instead of "Mode 1", the description doesn't match what actually happens:

Pressing the button once shows this pattern, like in the documentation:

![image](https://user-images.githubusercontent.com/2480569/225990116-e439b4bc-a7cb-46c1-8585-e196aed4f5f0.png)

But the colors are different. Most buttons are light blue and the highlighted ones are darker blue. So the actual colors of the buttons do not match the colors in the documentation. Either the programming should be changed so that the actual colors match the documentation, or the documentation should be updated, saying which colors to expect on which Launchpad models.

> Press User Mode 1 button once again, button turns green, activating the Device Controller. Once more the button will turn red, activating the plain old User Mode 1 in case you need it.

Pressing the same button again goes to dark purple/light purple buttons that seem to act as vertical sliders for _something_. But the pattern doesn't resemble "scale edition mode" from the documentation in any way.

Pressing the same button three or more times has no effect, it just cycles between the light/dark blue and the light/dark purple.

At this point I am lost, I cannot see much similarity between what is described in the documentation and what is actually going on on the device.

**Comment by hdavid** [comment]
as you would understand, i cannot support all launchpad models and tell which model has which button label.
also the colors on the documentation are from the mk1 launchpads.

please give it a bit of time to learn. i did that on my free time, years ago and still try to make it work.

note: the status bar of ableton live give tons of information about mode switches of lp95.

**Comment by probonopd** [comment]
Yes, I fully undertand that you can't possbily document this for every model.
I'd be happy to help with documenting things for the Launchpad X (and I think Mini, which I believe has the same buttons).

Would you be interested in an updated (or second) documentation, and would you be willing to help be a bit (e.g., explaining what is a bug vs. works as intended) when I am stuck?

Thanks for this increadibly useuful piece of software!

**Comment by hdavid** [comment]
honestly, i think the documentation is already dense enough, if on top of that we add all variants of all launchpads... welll it is going to be unreadable.
