### ISSUE TITLE
Launchpad95 - Clip Color not correct.

### ISSUE THREAD

**Issue by ThaBonziStudio** [hdavid/Launchpad95#79]
Hello!
The clip colors in session and prosession pages is not correct, it's different from abl color clips.
They are all light colors, red is pink, brown purple and gray and they are different.
Is it possible to correct the CLIP COLOR TABLE?
Thanks.

![IMG_5996](https://user-images.githubusercontent.com/129505155/229096065-8fcd0d68-aca6-4b6a-899d-23efd34de036.jpg)
<img width="650" alt="Schermata 2023-03-31 alle 12 25 08" src="https://user-images.githubusercontent.com/129505155/229096082-2e368cb5-9a99-4b47-80ce-1fce0f0a2658.png">

**Comment by hdavid** [comment]
i had a look at it, i tried to update the color tables from this files: (it seems different from the one i had)
https://github.com/gluon/AbletonLive11_MIDIRemoteScripts/blob/main/novation/colors.py
the colors a bit better, but not great. especially the red tones.

i add a look and could not understand why the original LPX script shows different colors. it seems to use this table too.

if you find a way to fix it, let me know !

**Comment by ThaBonziStudio** [comment]
> i had a look at it, i tried to update the color tables from this files: (it seems different from the one i had) https://github.com/gluon/AbletonLive11_MIDIRemoteScripts/blob/main/novation/colors.py the colors a bit better, but not great. especially the red tones.
> 
> i add a look and could not understand why the original LPX script shows different colors. it seems to use this table too.
> 
> if you find a way to fix it, let me know !

Maybe I understood!
The colors are right, but a command tells session and prosession to read them in a light shade!!
Here I pass the ball to you, I'm not capable!

**Comment by hdavid** [comment]
happy to have a look, can you point me to the file/line of code you found ? (pro-session code is not made by me)

**Comment by ThaBonziStudio** [comment]
> happy to have a look, can you point me to the file/line of code you found ? (pro-session code is not made by me)

I don't have the slightest idea, I don't understand anything!!!

**Comment by ThaBonziStudio** [comment]
News?

**Comment by ThaBonziStudio** [comment]
I test with delete all clip color list (CLIP_COLOR_TABLE = {})
Don't change! Where takes the color with the empty list???

**Comment by ThaBonziStudio** [comment]
News? Never?

**Comment by ThaBonziStudio** [comment]
Hello! News??

**Comment by ThaBonziStudio** [comment]
Finally I managed to adjust the colors of the clips!!!
Thanks for all the help you Didn't give me.
As you told me in an email: good luck!
![ok](https://user-images.githubusercontent.com/129505155/233798155-6b6ff9bb-b78d-484d-b209-526289a5811d.jpg)

**Comment by hdavid** [comment]
Hi @ThaBonziStudio,

i have been travelling the last few weeks, without my launchpad. i gave it a try quickly back then and could not figure out how to fix it. And after that i did not get a chance to dive further into the matter.

Note that i built and try to maintain LP95 absolutely for free (the donations barely covered the costs of buying new models of launchpad to test compatiblity). 

I am happy that you could get the colours right :)  

If you feel like it, i am sure all the users of Launchpad95 scripts would be super happy to get their colors rights too. That's what is nice with opensource, everybody benefits from the work of everybody. Feel free to share the fix as a pull request, a diff, an email or any other mean you see fit.
I would totally understand if you would not want to share the results of your work, eventhough, personally, i find it goes a bit against the philosphy of this project.

**Comment by ThaBonziStudio** [comment]
Hi @hdavid,
I understand very well that a person is busy, but in the last month that I asked you for news, you never deigned to reply. You could very well have told me you didn't have time, it would have taken you less than half the time it took you to answer me today!
With all due respect, I felt abandoned by you.
Anyway I have already congratulated you for the splendid script you made, I will gladly tell you how I solved it: I changed 70 colors of the RGB_COLOR_TABLE, the solution was all there in the ColorMK2 page. ;)

**Comment by hdavid** [comment]
thanks for sharing :) i am currently travelling, but will test it as soon as possible.

**Comment by hdavid** [comment]
i finally got within reach of a computer and a LPX and could give it a go. it looks much better indeed. thanks for sharing again. appreciated.
i will make a release in the coming weeks.
