### ISSUE TITLE
stepless faders

### ISSUE THREAD

**Issue by MrMatch246** [hdavid/Launchpad95#80]
Would it be possible to implement stepless faders for the device controller? 

I think it should work like the following:
the higher the difference between current value and the wanted value, the higher the velocity.
I would implement it but i dont know where in all the python files this would happen if at all.

**Comment by hdavid** [comment]
that would only work on launchpad with velocity. the original firmware has something like this but it relies on a hardware feature being implemented on the launchpad, and not all launchpad have it. therefore it is not possible to implement for all launchpads.

**Comment by MrMatch246** [comment]
ah no, i meant the velocity with which the fader value changes

**Comment by MrMatch246** [comment]
That should work independent of the launchpad features itself.

**Comment by hdavid** [comment]
This has to be implemented in the firmware. The script can only react to on message and that’s it. It cannot generate series of values like you want.

**Comment by MrMatch246** [comment]
So these scripts DONT send the values to Ableton?

**Comment by CesarPantoja** [comment]
Not all Launchpads have velocity sensitive pads. How would you determine how fast or slow the change happens with a Launchpad that doesn't have velocity sensitive pads?

**Comment by hdavid** [comment]
This is not possible to implement. The script receive midi data and translate it into live api calls. It cannot generate the intermediates steps. For this reason this feature was implemented as a hardware hack in the firmware on the pro (and possibly other ones)

**Comment by MrMatch246** [comment]
Okay i think i shold have been more precise with my request, my bad.

I would like to have the following behavior: 

In the DeviceControl page there are 8 sliders that control (basically any) parameters that ableton is able to control in a VST, e.g. Modwheel in a synth. These Sliders are currently behaving like a list of buttons where each one sets the value of a parameter to one of 8 predefined values. As this is not so nice for e.g. LP Filter i would like this value change to happen over time:
Lets assume the value is currently 0 (only lowest button is lit) and i press the highest, then i would like to have a a change that happens (in this case quick ) over time an not instantaneous from 0 to 1 but rather something like (0 ; 0.25 ; 0.5 ; 0.75 ; 1.0)

the number of steps in between is controlled by how far the current value and the wanted one is ,

so if in the above example i would have clicked the second from the bottom i would want the change to happen slower ( speed not time) 

I think it makes sense that every change happens within one second but not instantaneous.
Does this make sense?

**Comment by hdavid** [comment]
like i said, the script cannot generate multiple values over time.

**Comment by MrMatch246** [comment]
Could you please explain why? (GIL? concurrency?)

**Comment by hdavid** [comment]
i did not write live so i wont be able to give you an exact anwser. but i remember trying something over 10 years ago and it ended up crashing live. and that correlates with novation implementing the hack in the firmware.

**Comment by MrMatch246** [comment]
As i didnt want to leave it there :D i implemented it myself BUT i think its quite hacky so far and would like your input to [this](https://github.com/MrMatch246/Launchpad95) .
I split the DeviceControllerStrip in two classes proxy and server which are connected by queues,
such that a call to _butto_value instantly returns (preventing the UI to freeze) and within the server the value will slowly be changed with the self._parameter_to_map_to.value = smth calls. (velocity is respected, Launchpads without velocity sensitive pads will probably just have a static change rate)
Currently value changes from outside the Launchpad arent respected yet so i will fix this before issuing a pull request
