### ISSUE TITLE
Cannot edit notes in the sequencer

### ISSUE THREAD

**Issue by buscon** [hdavid/Launchpad95#82]
hi,

I am using a launchpad MK1 with the lanuchpad95 and Live 11. I downloaded the script from [https://motscousus.com/stuff/2011-07_No ... e_Scripts/](https://motscousus.com/stuff/2011-07_Novation_Launchpad_Ableton_Live_Scripts/)
and carefully followed the instructions.
 
The drum templates (the colors) appear on the launchpad and the sequencer runs and show the notes which are already present in the mdi clip but when I press the buttons nothing change in the midi clip in Live, i.e. I cannot edit (delete or add) notes of the midi clip.
If I press "user 2" button for long time, it also does not turn green, so I cannot access the MelodicStepSequencer.

What could be the problem?
MIDI in/out is already activated in the Live midi preferences.

**Comment by MrMatch246** [comment]
can you press the notes that are already in the midi clip in the sequencer, will they get removed? which sequencer are u using?
Maybe you didnt select the right part of the clip in the sequencer

**Comment by buscon** [comment]
I am indeed in session view, the clip is selected correctly.
I do see the notes on the launchpad with green colors and the yellow metronome. if I press such notes:
1. in multimode, the color on the launchpad goes off and on, but nothing happens in the midi clip
2. in combined mode, nothing happens if I click on the launchpad pads (they do not change color) and also nothing happens in the midi clip in Live
3. I do not know how to get to the MelodicStepSequencer, however I click "user 2" I only cycle between multimode and combined mode

**Comment by MrMatch246** [comment]
What Launchpad do you have? 
go to the drum sequencer and press the 4th button on the right
this should open the multinote mode user 2 should cycle drum and melodic step sequencer

**Comment by buscon** [comment]
I have the launchpad first version, mk1.
and yes, if I press the 4th button on the right I an cycle between the two modes, though I still cannot edit the notes. Nothing changes in the midi clip in live.

**Comment by buscon** [comment]
I figured out the problem testing the setup on another computer.
Live displayed this warning issue: https://motscousus.com/stuff/2011-07_Novation_Launchpad_Ableton_Live_Scripts/live11-api.png
I accidentally pressed deny and do not show again for this device.

Do you know how I can change this setting?

**Comment by hdavid** [comment]
hi, i am happy you found the reason in particular because i dont own a mk1 launchpad to test on anymore!
as for reverting the warning, i dont know. maybe try to unsetup the controller in ableton preferences and set it up again ? otherwise you will have to ask ableton support i am affraid :/

**Comment by buscon** [comment]
thank you for your answer, at least it is not an issue of your software.

**Comment by MrMatch246** [comment]
Resetting ableton works , search for how to reset user preferences in ableton

**Comment by buscon** [comment]
> Resetting ableton works , search for how to reset user preferences in ableton

did it, now it works! thank you :)
