### ISSUE TITLE
Toggling between the Drum StepSequencer and the Melodic StepSequencer stops the Drum StepSequencer from working for the rest of the session

### ISSUE THREAD

**Issue by mentalfoundry** [hdavid/Launchpad95#85]
Tested on a new ableton 11.3.10 project with a launchpad mini mk3.

1) Plug in launchpad.
2) Open ableton and create a new project and add some drums to a midi track.
3) Browse to Drum StepSequencer and see that it works.
4) Toggle to Melodic sequencer and see that it works also.
5) Toggle back to Drum StepSequencer and see that it no longer works.
6) Toggling back to Melodic sequencer is fine but Drum StepSequencer will no longer work.

**Comment by mentalfoundry** [comment]
Fix for issue is in this PR. https://github.com/hdavid/Launchpad95/pull/86

**Comment by hdavid** [comment]
thanks for spotting it and even more so for fixing it! 
i will check the PR in the comming days, and merge to master.

**Comment by hdavid** [comment]
strange, i had a go at it, using the version of the code in this repository (not released on my site yet), from master branch.
i could switch between drum step sequencer, melodic step sequencer (pressing the 3rd mode button), and multi note mode from the drum sequencer (using 4th scene button), multiple times, adding and removing notes every time. no issue.
with live 11.3.10 on macos.

can you reproduce with the code from master ? if so can you give more detailed steps?

i also tested the code from your PR. no difference.

**Comment by mentalfoundry** [comment]
You are correct, it seems this issue is only on the release on the website. Confirm its fine on Master - however I think the ordering here might still be worth updating to follow what's in the melodic sequencer. Reset code on top, then do things. This way it's still a little more robust than before.

**Comment by hdavid** [comment]
agreed!
